admin_v2:
    path:  /
    defaults: { _controller: AppBundle:Admin/Default:index }

#测试测试菜单展示
admin_v2_user:
    path:  /user
    defaults: { _controller: AppBundle:Admin/User:index }
    permissions: [admin_user_manage]

#测试测试菜单展示
admin_v2_user_create:
    path:  /user/create
    defaults: { _controller: AppBundle:Admin/User:create }

#测试测试菜单展示
admin_v2_user_learn_statistics:
    path:  /user/create
    defaults: { _controller: AppBundle:Admin/User:show }
    permissions: [admin]

#测试测试菜单展示
admin_v2_online:
    path:  /user/create
    defaults: { _controller: AppBundle:Admin/User:show }
    permissions: [admin]

#测试测试菜单展示
admin_v2_login_record:
    path:  /user/create
    defaults: { _controller: AppBundle:Admin/User:show }
    permissions: [admin]

# 教学-课程管理-课程管理
admin_v2_course_set:
    path:  /course_set/index
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:index }
    permissions: [admin_v2_course_manage]

admin_v2_course_list:
    path:  /course_set/{id}/course/list
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:courseList }
    permissions: [admin_v2_course_manage]

admin_v2_course_set_clone_by_web:
    path:  /course_set/{courseSetId}/clone_by_web
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:cloneByWeb }
    permissions: [admin_v2_course_manage]
    methods: [POST]

admin_v2_course_set_clone_by_crontab:
    path:  /course_set/{courseSetId}/clone_by_crontab
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:cloneByCrontab }
    permissions: [admin_v2_course_manage]
    methods: [POST]

admin_v2_course_set_delete:
    path:  /course_set/{id}/delete/{type}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:delete, type:'' }
    permissions: [admin_v2_course_manage]

admin_v2_course_set_clone:
    path:  /course_set/{courseSetId}/clone
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:clone, type:'web' }
    permissions: [admin_v2_course_manage]

admin_v2_course_set_publish:
    path: /course_set/{id}/publish
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:publish }
    methods: [POST]
    permissions: [admin_v2_course_manage]

admin_v2_course_set_close:
    path: /course_set/{id}/close
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:close }
    methods: [POST]
    permissions: [admin_v2_course_set_close]

admin_v2_course_set_recommend:
    path: /course_set/{id}/recommend
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:recommend }
    permissions: [admin_v2_course_set_recommend_list, admin_v2_course_set_recommend]

admin_v2_course_set_cancel_recommend:
    path: /course_set/{id}/recommend/cancel/{target}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:cancelRecommend }
    methods: [POST]
    permissions: [admin_v2_course_set_recommend_list, admin_v2_course_set_cancel_recommend]

admin_v2_course_chooser:
    path: /course_set/chooser
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:chooser }

admin_v2_course_set_recommend_list:
    path: /course_set/recommend/list
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:recommendList }

admin_v2_course_set_data:
    path:  /course_set/{filter}/data
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:dataList , filter:'normal'}

course_v2_set_detail_data:
    path:  /course_set/detail/data/{id}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:detailData }

admin_v2_course_tag_match:
    path:  /course_set/tag/match
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:courseTagMatch }

admin_v2_course_set_detail_data:
    path:  /course_set/detail/data/{id}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:detailData }

admin_v2_courses_data:
    path:  /courses/data/{courseSetId}
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:coursesData }
    permissions: [admin_v2_course_set_data]

admin_v2_course_task_data_export_prepare:
    path: /course/{courseId}/datas/export/prepare
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:prepareForExportTasksDatas}
    permissions: [admin_v2_course_set_data]

admin_v2_course_task_data_export:
    path: /course/{courseId}/datas/export
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:exportTaskDatas}

admin_v2_check_password:
    path:  /check/password
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:checkPassword }
    permissions: [admin_v2_course_manage]

# 教学-课程管理-班级管理
admin_v2_classroom:
    path:     /classroom/index
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:index }

admin_v2_classroom_create:
    path:  /classroom/create
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:create }

admin_v2_classroom_set_recommend:
    path:   /classroom/{id}/recommend
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:recommend }
    permissions: [admin_v2_classroom_set_recommend]

admin_v2_classroom_cancel_recommend:
    path:   /classroom/{id}/recommend/cancel
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:cancelRecommend }
    permissions: [admin_v2_classroom_cancel_recommend]

admin_v2_classroom_close:
    path:  /classroom/{id}/close
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:close }
    methods: [POST]

admin_v2_classroom_open:
    path:  /classroom/{id}/open
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:open }
    methods: [POST]

admin_v2_classroom_delete:
    path:  /classroom/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:delete }
    methods: [POST]

admin_v2_classroom_recommend_list:
    path:   /classroom/recommend/list
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:recommendIndex }

# 教学-课程管理-公开课管理
admin_v2_open_course:
    path: /open_course/{filter}
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:index, filter:'open' }

admin_v2_open_course_recommend_list:
    path: /open_course/recommend/list
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:recommendList }

admin_v2_open_course_delete:
    path: /open_course/{courseId}/delete/{type}
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:delete, type:'' }
    methods: [POST]

admin_v2_open_course_publish:
    path: /open_course/{id}/publish
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:publish }
    methods: [POST]

admin_v2_open_course_close:
    path: /open_course/{id}/close
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:close }
    methods: [POST]

admin_v2_open_course_recommend:
    path: /open_course/{id}/recommend
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:recommend }

admin_v2_open_course_cancel_recommend:
    path: /open_course/{id}/recommend/cancel/{target}
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:cancelRecommend }
    methods: [POST]

admin_v2_open_course_analysis:
    path:  /open_course/analysis/index
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:index }

admin_v2_open_course_analysis_referer_summary_list:
    path:  /open_course/analysis/referer/list
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:summaryList }

admin_v2_open_course_analysis_referer_summary:
    path:  /open_course/analysis/referer/summary
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:summary }

admin_v2_open_course_analysis_referer_watch_statistics:
    path: /open_course/analysis/watch
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:watch }

admin_v2_open_course_analysis_referer_detail:
    path:  /open_course/{id}/analysis/referer/detail
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:detail }

admin_v2_open_course_analysis_referer_detail_list:
    path:  /open_course/{id}/analysis/referer/detailList
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:detailList }

admin_v2_open_course_analysis_conversion:
    path:  open_course/analysis/conversion
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:conversion }

admin_v2_open_course_analysis_conversion_result:
    path:  /open_course/{courseId}/analysis/conversion/result
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:conversionResult }

# 教学-助学管理-笔记管理
admin_v2_course_note:
    path: /note
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:noteList }
    permissions: [admin_v2_course_note_manage]

admin_v2_note_delete:
    path: /note/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:deleteNote }
    methods: [POST]
    permissions: [admin_v2_course_note_manage]

admin_v2_note_batch_delete:
    path: /note/batch_delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:batchDeleteNote }
    methods: [POST]
    permissions: [admin_v2_course_note_manage]

# 教学-助学管理-问答管理
admin_v2_question:
    path:  /question/{postStatus}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseQuestion:index }
    permissions: [admin_v2_course_question_manage]

# 教学-助学管理-话题管理
admin_v2_course_thread:
    path:  /thread
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:courseThreadIndex }
    permissions: [admin_v2_course_thread]

admin_v2_course_thread_delete:
    path: /thread/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:courseThreadDelete }
    methods: [POST]
    permissions: [admin_v2_course_thread, admin_v2_course_question_manage]

admin_v2_course_thread_batch_delete:
    path: /thread/batch_delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:courseThreadBatchDelete }
    methods: [POST]
    permissions: [admin_v2_course_thread]

admin_v2_classroom_thread:
    path:     /classroom/thread
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:classroomThreadIndex }

admin_v2_classroom_thread_delete:
    path:     /classroom/thread/{threadId}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:classroomThreadDelete }
    methods: [POST]
  
#反馈管理
admin_v2_course_review:
    path:  /course/review
    defaults: { _controller: AppBundle:AdminV2/Teach/Review:courseReviewList }
    permissions: [admin_v2_course_review_tab]

admin_v2_course_review_delete:
    path: /course/review/{id}/delete
    defaults: {_controller: AppBundle:AdminV2/Teach/Review:deleteCourseReview }
    methods: [POST]
    permissions: [admin_v2_course_review_tab]

admin_v2_course_review_batch_delete:
    path: /course/review/batch_delete
    defaults: {_controller: AppBundle:AdminV2/Teach/Review:batchDeleteCourseReview }
    methods: [POST]
    permissions: [admin_v2_course_review_tab]

admin_v2_classroom_review:
    path:  /classroom/review
    defaults: { _controller: AppBundle:AdminV2/Teach/Review:classroomReviewList }
    permissions: [admin_v2_classroom_review_tab]

admin_v2_classroom_thread_batch_delete:
    path:     /classroom/thread/batch_delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:classroomThreadBatchDelete }

admin_v2_classroom_review_delete:
    path:  /classroom/review/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Review:deleteClassroomReview }
    methods: [POST]
    permissions: [admin_v2_classroom_review_tab]

admin_v2_classroom_review_batch_delete:
    path:  /classroom/review/batch_delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Review:batchDeleteClassroomReview }
    methods: [POST]
    permissions: [admin_v2_classroom_review_tab]

#运营-渠道管理-分销
admin_v2_login_distributor:
    path: /login/distributor
    defaults: { _controller: AppBundle:AdminV2/Marketing/Distributor:login }
  
#用户
##用户管理
admin_v2_user_show:
    path:  /user/{id}
    defaults: { _controller: AppBundle:AdminV2/User/User:show }
    permissions: [admin_v2]

# 系统
## 组织机构管理
admin_v2_batch_update_org:
    path:  batch/update/{module}/org
    defaults: { _controller: AppBundle:AdminV2/System/OrgManage:batchUpdate }

# 通用
admin_v2_sms_prepare:
    path:  /sms/prepare/{targetType}/{id}
    defaults: { _controller: AppBundle:AdminV2/Sms:prepare }

admin_v2_publish_sms_send:
    path:  /publish/sms_send/{targetType}/{id}
    defaults: { _controller: AppBundle:AdminV2/Sms:send }

admin_v2_generate_short_link:
    path:  /generate/short/link
    defaults: { _controller: AppBundle:AdminV2/Sms:changeLink }

admin_v2_question_remind_teachers:
    path: /course/{courseId}/question/{questionId}/remindTeachers
    defaults: { _controller: AppBundle:AdminV2/Default:questionRemindTeachers }
    methods:  [POST]
    permissions: [admin_v2]
#教学
##分类标签
admin_v2_course_category:
    path: /course/category
    defaults: { _controller: AppBundle:AdminV2/Teach/Category:courseCategory }
    permissions: [admin_v2_course_category_manage]

admin_v2_classroom_category:
    path: /classroom/category
    defaults: { _controller: AppBundle:AdminV2/Teach/Category:classroomCategory }

admin_v2_category_create:
    path: /category/create
    defaults: { _controller: AppBundle:AdminV2/Teach/Category:create }

admin_v2_category_edit:
    path:  /category/{id}/edit
    defaults: { _controller: AppBundle:AdminV2/Teach/Category:edit }
    permissions: [admin_v2_course_category_manage]

admin_v2_category_delete:
    path:  /category/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Category:delete }
    methods: [POST]

admin_v2_category_sort:
    path:  /category/sort
    defaults: { _controller: AppBundle:AdminV2/Teach/Category:sort }
    methods: [POST]

admin_v2_category_checkcode:
    path:  /category/checkcode
    defaults: { _controller: AppBundle:AdminV2/Teach/Category:checkCode }
    permissions: [admin_v2_course_category_manage]

admin_v2_tag:
    path:  /tag
    defaults: { _controller: AppBundle:AdminV2/Teach/Tag:index }
    permissions: [admin_v2_course_tag_manage]

admin_v2_tag_create:
    path:  /tag/create
    defaults: { _controller: AppBundle:AdminV2/Teach/Tag:create }
    permissions: [admin_v2_course_tag_add]

admin_v2_tag_update:
    path:  /tag/{id}/update
    defaults: { _controller: AppBundle:AdminV2/Teach/Tag:update }
    permissions: [admin_v2_course_tag_manage]

admin_v2_tag_delete:
    path:  /tag/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Tag:delete }
    methods:  [POST]
    permissions: [admin_v2_course_tag_manage]

admin_v2_tag_checkname:
    path:  /tag/checkname
    defaults: { _controller: AppBundle:AdminV2/Teach/Tag:checkName}
    permissions: [admin_v2_course_tag_manage]

admin_v2_tag_group:
    path: /tag/group
    defaults: { _controller: AppBundle:AdminV2/Teach/TagGroup:index }

admin_v2_tag_group_update:
    path: /tag/group/{groupId}/update
    defaults: { _controller: AppBundle:AdminV2/Teach/TagGroup:update }

admin_v2_tag_group_create:
    path: /tag/group/create
    defaults: { _controller: AppBundle:AdminV2/Teach/TagGroup:create }

admin_v2_tag_group_delete:
    path: /tag/group/{tagId}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/TagGroup:delete }

admin_v2_tag_group_checkname:
    path: /tag/group/checkname
    defaults: { _controller: AppBundle:AdminV2/Teach/TagGroup:checkName }

# 应用中心-云服务-短信概览
admin_v2_edu_cloud_sms:
    path:  /edu_cloud/sms/overview
    defaults: { _controller: AppBundle:AdminV2/CloudCenter/CloudServer:smsOverview }
    permissions: [admin_v2_edu_cloud_sms_overview]

#营销-营销管理-邀请管理
admin_v2_invite_record:
    path:  /invite/record
    defaults: { _controller: AppBundle:AdminV2/Marketing/Invite:record }
    permissions: [admin_v2_operation_invite]

admin_v2_invite:
    path:  /invite
    defaults: { _controller: AppBundle:AdminV2/Marketing/Invite:userRecords }
    permissions: [admin_v2_operation_invite]

admin_v2_invite_coupon:
    path: /invite/{filter}/coupon/
    defaults: { _controller: AppBundle:AdminV2/Marketing/Invite:coupon, filter:'invited'}

admin_v2_invite_coupon_query:
    path: /invite/coupon/query/
    defaults: { _controller: AppBundle:AdminV2/Marketing/Invite:queryInviteCoupon }

admin_v2_invite_detail:
    path:  /invite/detail
    defaults: { _controller: AppBundle:AdminV2/Marketing/Invite:inviteDetail }
    permissions: [admin_v2_operation_invite]

admin_v2_invite_set:
    path:  /setting/invite
    defaults: { _controller: AppBundle:Admin/OperationSetting:inviteSet }
