admin_v2:
    path:  /
    defaults: { _controller: AppBundle:Admin/Default:index }

#测试测试菜单展示
admin_v2_user:
    path:  /user
    defaults: { _controller: AppBundle:Admin/User:index }
    permissions: [admin_user_manage]

#测试测试菜单展示
admin_v2_user_create:
    path:  /user/create
    defaults: { _controller: AppBundle:Admin/User:create }

#测试测试菜单展示
admin_v2_user_learn_statistics:
    path:  /user/create
    defaults: { _controller: AppBundle:Admin/User:show }
    permissions: [admin]

#测试测试菜单展示
admin_v2_online:
    path:  /user/create
    defaults: { _controller: AppBundle:Admin/User:show }
    permissions: [admin]

#测试测试菜单展示
admin_v2_login_record:
    path:  /user/create
    defaults: { _controller: AppBundle:Admin/User:show }
    permissions: [admin]

# 教学-课程管理-课程管理
admin_v2_course_set:
    path:  /course_set/index
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:index }
    permissions: [admin_v2_course_manage]

admin_v2_course_list:
    path:  /course_set/{id}/course/list
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:courseList }
    permissions: [admin_v2_course_manage]

admin_v2_course_set_clone_by_web:
    path:  /course_set/{courseSetId}/clone_by_web
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:cloneByWeb }
    permissions: [admin_v2_course_manage]
    methods: [POST]

admin_v2_course_set_clone_by_crontab:
    path:  /course_set/{courseSetId}/clone_by_crontab
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:cloneByCrontab }
    permissions: [admin_v2_course_manage]
    methods: [POST]

admin_v2_course_set_delete:
    path:  /course_set/{id}/delete/{type}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:delete, type:'' }
    permissions: [admin_v2_course_manage]

admin_v2_course_set_clone:
    path:  /course_set/{courseSetId}/clone
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:clone, type:'web' }
    permissions: [admin_v2_course_manage]

admin_v2_course_set_publish:
    path: /course_set/{id}/publish
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:publish }
    methods: [POST]
    permissions: [admin_v2_course_manage]

admin_v2_course_set_close:
    path: /course_set/{id}/close
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:close }
    methods: [POST]
    permissions: [admin_v2_course_set_close]

admin_v2_course_set_recommend:
    path: /course_set/{id}/recommend
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:recommend }
    permissions: [admin_v2_course_set_recommend_list, admin_v2_course_set_recommend]

admin_v2_course_set_cancel_recommend:
    path: /course_set/{id}/recommend/cancel/{target}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:cancelRecommend }
    methods: [POST]
    permissions: [admin_v2_course_set_recommend_list, admin_v2_course_set_cancel_recommend]

admin_v2_course_chooser:
    path: /course_set/chooser
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:chooser }

admin_v2_course_set_recommend_list:
    path: /course_set/recommend/list
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:recommendList }

admin_v2_course_set_data:
    path:  /course_set/{filter}/data
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:dataList , filter:'normal'}

course_v2_set_detail_data:
    path:  /course_set/detail/data/{id}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:detailData }

admin_v2_course_tag_match:
    path:  /course_set/tag/match
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:courseTagMatch }

admin_v2_course_set_detail_data:
    path:  /course_set/detail/data/{id}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:detailData }

admin_v2_courses_data:
    path:  /courses/data/{courseSetId}
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:coursesData }
    permissions: [admin_v2_course_set_data]

admin_v2_course_task_data_export_prepare:
    path: /course/{courseId}/datas/export/prepare
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:prepareForExportTasksDatas}
    permissions: [admin_v2_course_set_data]

admin_v2_course_task_data_export:
    path: /course/{courseId}/datas/export
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:exportTaskDatas}

admin_v2_check_password:
    path:  /check/password
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:checkPassword }
    permissions: [admin_v2_course_manage]

# 教学-课程管理-班级管理
admin_v2_classroom:
    path:     /classroom/index
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:index }

admin_v2_classroom_create:
    path:  /classroom/create
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:create }

admin_v2_classroom_set_recommend:
    path:   /classroom/{id}/recommend
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:recommend }
    permissions: [admin_v2_classroom_set_recommend]

admin_v2_classroom_cancel_recommend:
    path:   /classroom/{id}/recommend/cancel
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:cancelRecommend }
    permissions: [admin_v2_classroom_cancel_recommend]

admin_v2_classroom_close:
    path:  /classroom/{id}/close
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:close }
    methods: [POST]

admin_v2_classroom_open:
    path:  /classroom/{id}/open
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:open }
    methods: [POST]

admin_v2_classroom_delete:
    path:  /classroom/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:delete }
    methods: [POST]

admin_v2_classroom_recommend_list:
    path:   /classroom/recommend/list
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:recommendIndex }

# 教学-课程管理-公开课管理
admin_v2_open_course:
    path: /open_course/{filter}
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:index, filter:'open' }

admin_v2_open_course_recommend_list:
    path: /open_course/recommend/list
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:recommendList }

admin_v2_open_course_delete:
    path: /open_course/{courseId}/delete/{type}
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:delete, type:'' }
    methods: [POST]

admin_v2_open_course_publish:
    path: /open_course/{id}/publish
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:publish }
    methods: [POST]

admin_v2_open_course_close:
    path: /open_course/{id}/close
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:close }
    methods: [POST]

admin_v2_open_course_recommend:
    path: /open_course/{id}/recommend
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:recommend }

admin_v2_open_course_cancel_recommend:
    path: /open_course/{id}/recommend/cancel/{target}
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:cancelRecommend }
    methods: [POST]

admin_v2_open_course_analysis:
    path:  /open_course/analysis/index
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:index }

admin_v2_open_course_analysis_referer_summary_list:
    path:  /open_course/analysis/referer/list
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:summaryList }

admin_v2_open_course_analysis_referer_summary:
    path:  /open_course/analysis/referer/summary
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:summary }

admin_v2_open_course_analysis_referer_watch_statistics:
    path: /open_course/analysis/watch
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:watch }

admin_v2_open_course_analysis_referer_detail:
    path:  /open_course/{id}/analysis/referer/detail
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:detail }

admin_v2_open_course_analysis_referer_detail_list:
    path:  /open_course/{id}/analysis/referer/detailList
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:detailList }

admin_v2_open_course_analysis_conversion:
    path:  open_course/analysis/conversion
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:conversion }

admin_v2_open_course_analysis_conversion_result:
    path:  /open_course/{courseId}/analysis/conversion/result
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourseAnalysis:conversionResult }

# 教学-助学管理-笔记管理
admin_v2_course_note:
    path: /note
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:noteList }
    permissions: [admin_v2_course_note_manage]

admin_v2_note_delete:
    path: /note/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:deleteNote }
    methods: [POST]
    permissions: [admin_v2_course_note_manage]

admin_v2_note_batch_delete:
    path: /note/batch_delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:batchDeleteNote }
    methods: [POST]
    permissions: [admin_v2_course_note_manage]

# 教学-助学管理-问答管理
admin_v2_question:
    path:  /question/{postStatus}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseQuestion:index }
    permissions: [admin_v2_course_question_manage]

# 教学-助学管理-话题管理
admin_v2_course_thread:
    path:  /thread
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:courseThreadIndex }
    permissions: [admin_v2_course_thread]

admin_v2_course_thread_delete:
    path: /thread/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:courseThreadDelete }
    methods: [POST]
    permissions: [admin_v2_course_thread, admin_v2_course_question_manage]

admin_v2_course_thread_batch_delete:
    path: /thread/batch_delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:courseThreadBatchDelete }
    methods: [POST]
    permissions: [admin_v2_course_thread]

admin_v2_classroom_thread:
    path:     /classroom/thread
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:classroomThreadIndex }

admin_v2_classroom_thread_delete:
    path:     /classroom/thread/{threadId}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:classroomThreadDelete }
    methods: [POST]
  
#反馈管理
admin_v2_course_review:
    path:  /course/review
    defaults: { _controller: AppBundle:AdminV2/Teach/Review:courseReviewList }
    permissions: [admin_v2_course_review_tab]

admin_v2_course_review_delete:
    path: /course/review/{id}/delete
    defaults: {_controller: AppBundle:AdminV2/Teach/Review:deleteCourseReview }
    methods: [POST]
    permissions: [admin_v2_course_review_tab]

admin_v2_course_review_batch_delete:
    path: /course/review/batch_delete
    defaults: {_controller: AppBundle:AdminV2/Teach/Review:batchDeleteCourseReview }
    methods: [POST]
    permissions: [admin_v2_course_review_tab]

admin_v2_classroom_review:
    path:  /classroom/review
    defaults: { _controller: AppBundle:AdminV2/Teach/Review:classroomReviewList }
    permissions: [admin_v2_classroom_review_tab]

admin_v2_classroom_thread_batch_delete:
    path:     /classroom/thread/batch_delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:classroomThreadBatchDelete }

admin_v2_classroom_review_delete:
    path:  /classroom/review/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Review:deleteClassroomReview }
    methods: [POST]
    permissions: [admin_v2_classroom_review_tab]

admin_v2_classroom_review_batch_delete:
    path:  /classroom/review/batch_delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Review:batchDeleteClassroomReview }
    methods: [POST]
    permissions: [admin_v2_classroom_review_tab]

#运营-渠道管理-分销
admin_v2_login_distributor:
    path: /login/distributor
    defaults: { _controller: AppBundle:AdminV2/Marketing/Distributor:login }
  
#用户
##用户管理
admin_v2_user_show:
    path:  /user/{id}
    defaults: { _controller: AppBundle:AdminV2/User/User:show }
    permissions: [admin_v2]

# 运营
## 站点设置管理
admin_v2_navigation:
    path:  /setting/navigation
    defaults: { _controller: AppBundle:AdminV2/Operating/Navigation:index }
    permissions: [admin_v2_top_navigation,admin_v2_foot_navigation]

admin_v2_navigation_seqs_update:
    path:  /setting/navigation/seqs/update
    defaults: { _controller: AppBundle:AdminV2/Operating/Navigation:updateSeqs }
    permissions: [admin_v2_top_navigation,admin_v2_foot_navigation]

admin_v2_navigation_create:
    path:  /setting/navigation/create
    defaults: { _controller: AppBundle:AdminV2/Operating/Navigation:create }
    permissions: [admin_v2_top_navigation,admin_v2_foot_navigation]

admin_v2_navigation_update:
    path:  /setting/navigation/{id}/update
    defaults: { _controller: AppBundle:AdminV2/Operating/Navigation:edit }
    permissions: [admin_v2_top_navigation,admin_v2_foot_navigation]

admin_v2_navigation_delete:
    path:  /setting/navigation/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Operating/Navigation:delete }
    methods: [POST]
    permissions: [admin_v2_top_navigation,admin_v2_foot_navigation]

admin_v2_setting_consult_setting:
    path:  /setting/consult-setting
    defaults: { _controller: AppBundle:AdminV2/Operating/SiteSetting:consultSetting }

admin_v2_setting_consult_upload:
    path:  /setting/consult-upload
    defaults: { _controller: AppBundle:AdminV2/Operating/SiteSetting:consultUpload }
    permissions: [admin_v2_setting_consult_setting]

admin_v2_setting_consult_webchat_delete:
    path:  /setting/consult-webchat-delete
    defaults: { _controller: AppBundle:AdminV2/Operating/SiteSetting:deleteWebchat }
    methods:  [POST]
    permissions: [admin_v2_setting_consult_setting]
    
admin_v2_setting_es_bar:
    path:  /setting/es-bar
    defaults: { _controller: AppBundle:AdminV2/Operating/SiteSetting:esBarSetting }

admin_v2_content:
    path:  /setting/content
    defaults: { _controller: AppBundle:AdminV2/Operating/Content:index }
    
admin_v2_content_create:
    path:  /content/create/{type}
    defaults: { _controller: AppBundle:AdminV2/Operating/Content:create }
    permissions: [admin_v2_content]

admin_v2_content_edit:
    path:  /content/{id}/edit
    defaults: { _controller: AppBundle:AdminV2/Operating/Content:edit }
    permissions: [admin_v2_content]

admin_v2_content_publish:
    path:  /content/{id}/publish
    defaults: { _controller: AppBundle:AdminV2/Operating/Content:publish }
    methods:  [POST]
    permissions: [admin_v2_content]

admin_v2_content_trash:
    path:  /content/{id}/trash
    defaults: { _controller: AppBundle:AdminV2/Operating/Content:trash }
    methods:  [POST]
    permissions: [admin_v2_content]

admin_v2_content_delete:
    path:  /content/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Operating/Content:delete }
    methods:  [POST]
    permissions: [admin_v2_content]

admin_v2_content_alias_check:
    path:  /content/alias/check
    defaults: { _controller: AppBundle:Admin/Content:aliasCheck }
    permissions: [admin_v2_content]

admin_v2_setting_share:
    path:  /setting/share
    defaults: { _controller: AppBundle:AdminV2/Operating/SiteSetting:share }
   
#web端装修
admin_v2_block:
    path:  /block/list-{category}
    defaults: { _controller: AppBundle:AdminV2/Operating/Block:index }
    
admin_v2_setting_theme:
    path:  /setting/theme
    defaults: { _controller: AppBundle:AdminV2/Operating/Theme:index }
    
# 系统
## 组织机构管理
admin_v2_batch_update_org:
    path:  batch/update/{module}/org
    defaults: { _controller: AppBundle:AdminV2/System/OrgManage:batchUpdate }

# 通用
admin_v2_sms_prepare:
    path:  /sms/prepare/{targetType}/{id}
    defaults: { _controller: AppBundle:AdminV2/Sms:prepare }

admin_v2_publish_sms_send:
    path:  /publish/sms_send/{targetType}/{id}
    defaults: { _controller: AppBundle:AdminV2/Sms:send }

admin_v2_generate_short_link:
    path:  /generate/short/link
    defaults: { _controller: AppBundle:AdminV2/Sms:changeLink }

admin_v2_question_remind_teachers:
    path: /course/{courseId}/question/{questionId}/remindTeachers
    defaults: { _controller: AppBundle:AdminV2/Default:questionRemindTeachers }
    methods:  [POST]
    permissions: [admin_v2]

# 应用中心-云服务-短信概览
admin_v2_edu_cloud_sms:
    path:  /edu_cloud/sms/overview
    defaults: { _controller: AppBundle:AdminV2/CloudCenter/CloudServer:smsOverview }
    permissions: [admin_v2_edu_cloud_sms_overview]
