admin_v2:
    path:  /
    defaults: { _controller: AppBundle:Admin/Default:index }

# 教学-课程管理-课程管理
admin_v2_course_set:
    path:  /course_set/index
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:index }
    permissions: [admin_v2_course_manage]

admin_v2_course_list:
    path:  /course_set/{id}/course/list
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:courseList }
    permissions: [admin_v2_course_manage]

admin_v2_course_set_clone_by_web:
    path:  /course_set/{courseSetId}/clone_by_web
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:cloneByWeb }
    permissions: [admin_v2_course_manage]
    methods: [POST]

admin_v2_course_set_clone_by_crontab:
    path:  /course_set/{courseSetId}/clone_by_crontab
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:cloneByCrontab }
    permissions: [admin_v2_course_manage]
    methods: [POST]

admin_v2_course_set_delete:
    path:  /course_set/{id}/delete/{type}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:delete, type:'' }
    permissions: [admin_v2_course_manage]

admin_v2_course_set_clone:
    path:  /course_set/{courseSetId}/clone
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:clone, type:'web' }
    permissions: [admin_v2_course_manage]

admin_v2_course_set_publish:
    path: /course_set/{id}/publish
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:publish }
    methods: [POST]
    permissions: [admin_v2_course_manage]

admin_v2_course_set_close:
    path: /course_set/{id}/close
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:close }
    methods: [POST]
    permissions: [admin_v2_course_set_close]

admin_v2_course_set_recommend:
    path: /course_set/{id}/recommend
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:recommend }
    permissions: [admin_v2_course_set_recommend_list, admin_v2_course_set_recommend]

admin_v2_course_set_cancel_recommend:
    path: /course_set/{id}/recommend/cancel/{target}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:cancelRecommend }
    methods: [POST]
    permissions: [admin_v2_course_set_recommend_list, admin_v2_course_set_cancel_recommend]

admin_v2_course_chooser:
    path: /course_set/chooser
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:chooser }

admin_v2_course_set_recommend_list:
    path: /course_set/recommend/list
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:recommendList }

admin_v2_course_set_data:
    path:  /course_set/{filter}/data
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:dataList , filter:'normal'}

course_v2_set_detail_data:
    path:  /course_set/detail/data/{id}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:detailData }

admin_v2_course_tag_match:
    path:  /course_set/tag/match
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:courseTagMatch }

admin_v2_course_set_detail_data:
    path:  /course_set/detail/data/{id}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseSet:detailData }

admin_v2_courses_data:
    path:  /courses/data/{courseSetId}
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:coursesData }
    permissions: [admin_v2_course_set_data]

admin_v2_course_task_data_export_prepare:
    path: /course/{courseId}/datas/export/prepare
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:prepareForExportTasksDatas}
    permissions: [admin_v2_course_set_data]

admin_v2_course_task_data_export:
    path: /course/{courseId}/datas/export
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:exportTaskDatas}

admin_v2_check_password:
    path:  /check/password
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:checkPassword }
    permissions: [admin_v2_course_manage]

# 教学-课程管理-班级管理
admin_v2_classroom:
    path:     /classroom/index
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:index }

admin_v2_classroom_create:
    path:  /classroom/create
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:create }

admin_v2_classroom_set_recommend:
    path:   /classroom/{id}/recommend
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:recommend }
    permissions: [admin_v2_classroom_set_recommend]

admin_v2_classroom_cancel_recommend:
    path:   /classroom/{id}/recommend/cancel
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:cancelRecommend }
    permissions: [admin_v2_classroom_cancel_recommend]

admin_v2_classroom_close:
    path:  /classroom/{id}/close
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:close }
    methods: [POST]

admin_v2_classroom_open:
    path:  /classroom/{id}/open
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:open }
    methods: [POST]

admin_v2_classroom_delete:
    path:  /classroom/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:delete }
    methods: [POST]

admin_v2_classroom_recommend_list:
    path:   /classroom/recommend/list
    defaults: { _controller: AppBundle:AdminV2/Teach/ClassroomAdmin:recommendIndex }

# 教学-课程管理-公开课管理
admin:
    path: /teach/open_course/{filter}
    defaults: { _controller: AppBundle:AdminV2/Teach/OpenCourse:index, filter:'open' }

# 教学-助学管理-笔记管理
admin_v2_course_note:
    path: /note
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:noteList }
    permissions: [admin_v2_course_note_manage]

admin_v2_note_delete:
    path: /note/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:deleteNote }
    methods: [POST]
    permissions: [admin_v2_course_note_manage]

admin_v2_note_batch_delete:
    path: /note/batch_delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Course:batchDeleteNote }
    methods: [POST]
    permissions: [admin_v2_course_note_manage]

# 教学-助学管理-问答管理
admin_v2_question:
    path:  /question/{postStatus}
    defaults: { _controller: AppBundle:AdminV2/Teach/CourseQuestion:index }
    permissions: [admin_v2_course_question_manage]

# 教学-助学管理-话题管理
admin_v2_course_thread:
    path:  /thread
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:courseThreadIndex }
    permissions: [admin_v2_course_thread]

admin_v2_course_thread_delete:
    path: /thread/{id}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:courseThreadDelete }
    methods: [POST]
    permissions: [admin_v2_course_thread, admin_v2_course_question_manage]

admin_v2_course_thread_batch_delete:
    path: /thread/batch_delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:courseThreadBatchDelete }
    methods: [POST]
    permissions: [admin_v2_course_thread]

admin_v2_classroom_thread:
    path:     /classroom/thread
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:classroomThreadIndex }

admin_v2_classroom_thread_delete:
    path:     /classroom/thread/{threadId}/delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:classroomThreadDelete }
    methods: [POST]

admin_v2_classroom_thread_batch_delete:
    path:     /classroom/thread/batch_delete
    defaults: { _controller: AppBundle:AdminV2/Teach/Thread:classroomThreadBatchDelete }

  
#用户
##用户管理
admin_v2_user_show:
    path:  /user/{id}
    defaults: { _controller: AppBundle:AdminV2/User/User:show }
    permissions: [admin_v2]

# 系统
## 组织机构管理
admin_v2_batch_update_org:
    path:  batch/update/{module}/org
    defaults: { _controller: AppBundle:AdminV2/System/OrgManage:batchUpdate }

# 通用
admin_v2_sms_prepare:
    path:  /sms/prepare/{targetType}/{id}
    defaults: { _controller: AppBundle:AdminV2/Sms:prepare }

admin_v2_publish_sms_send:
    path:  /publish/sms_send/{targetType}/{id}
    defaults: { _controller: AppBundle:AdminV2/Sms:send }

admin_v2_generate_short_link:
    path:  /generate/short/link
    defaults: { _controller: AppBundle:AdminV2/Sms:changeLink }

admin_v2_question_remind_teachers:
    path: /course/{courseId}/question/{questionId}/remindTeachers
    defaults: { _controller: AppBundle:AdminV2/Default:questionRemindTeachers }
    methods:  [POST]
    permissions: [admin_v2]
